apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextjs-blog
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nextjs-blog-ip
  labels:
    app: nextjs-blog
spec:
  backend:
    serviceName: nextjs-blog-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-blog-backend
  labels:
    app: nextjs-blog
spec:
  type: NodePort
  selector:
    app: nextjs-blog
    tier: web
  ports:
  - port: 8080
    targetPort: 3000