import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { AppContext } from '../appState/appState';
import styles from '../styles/Home.module.css'
import { subscribedCompanies } from './selection';

export default function Home() {

  const { globalState, changeState }  = useContext(AppContext);

  const { companies } = globalState;

  useEffect(() => {
    changeState({type: "SET_COMPANIES", payload: subscribedCompanies })
  }, [subscribedCompanies]);

  console.log(globalState)

  function setCompany(company) {
    changeState({type: "SET_COMPANY", payload: company})
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">POS App!</a>
        </h1>

        <p className={styles.description}>
          Select your company
        </p>

        <div className={styles.grid}>
          {companies.map( (company, key) => {
            return (
              <div className={styles.card} key={key} onClick={() => setCompany(company) }>
                  <img  src={company.logo} />
                  <h2>{company.name}</h2>
                  <p>{company.description}</p>
              </div>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
